<a href="https://colab.research.google.com/github/SatyamSingh-16/AI-Journey/blob/main/Pandas/Pandas_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [21, 25, np.nan, 35, 40],
    "Salary": [30000, 45000, 60000, np.nan, 100000],
    "Department": ["IT", "HR", "IT", "Finance", "IT"]
})

print(df["Department"].unique())
df["Department"].nunique()
print(df.isnull())
print(df.isnull().sum())
df.isna()
df.dropna()
df.duplicated()

['IT' 'HR' 'Finance']
    Name    Age  Salary  Department
0  False  False   False       False
1  False  False   False       False
2  False   True   False       False
3  False  False    True       False
4  False  False   False       False
Name          0
Age           1
Salary        1
Department    0
dtype: int64

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [4]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E", "F"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [30000, 45000, 60000, 75000, 50000, 80000],
    "Experience": [1, 2, 5, 8, 3, 7]
})

print(df)

print(df[df["Department"]=="IT"]["Salary"].mean())
print(df[df["Department"]=="HR"]["Salary"].mean())
print(df[df["Department"]=="Finance"]["Salary"].mean())

df.groupby("Department")["Salary"].mean()
df.groupby("Department")["Salary"].agg(["mean","min","max","std"])

  Name Department  Salary  Experience
0    A         IT   30000           1
1    B         HR   45000           2
2    C         IT   60000           5
3    D    Finance   75000           8
4    E         HR   50000           3
5    F         IT   80000           7
56666.666666666664
47500.0
75000.0

                    mean    min    max           std
Department
Finance     75000.000000  75000  75000           NaN
HR          47500.000000  45000  50000   3535.533906
IT          56666.666667  30000  80000  25166.114784

In [5]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E", "F"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [30000, 45000, 60000, 75000, 50000, 80000],
    "Experience": [1, 2, 5, 8, 3, 7]
})

print(df.groupby("Department")["Salary"].mean())
print(df.groupby('Department')["Salary"].max())
print(df.groupby("Department")["Name"].count())
# print(df.groupby("Department")["Salary","Experience"].agg(["mean","mean"]))
print(df.sort_values("Salary",ascending=False))

Department
Finance    75000.000000
HR         47500.000000
IT         56666.666667
Name: Salary, dtype: float64
Department
Finance    75000
HR         50000
IT         80000
Name: Salary, dtype: int64
Department
Finance    1
HR         2
IT         3
Name: Name, dtype: int64
  Name Department  Salary  Experience
5    F         IT   80000           7
3    D    Finance   75000           8
2    C         IT   60000           5
4    E         HR   50000           3
1    B         HR   45000           2
0    A         IT   30000           1

In [16]:
import numpy as np
import pandas as pd

customers = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4, 5],
    "Name": ["A", "B", "C", "D", "E"],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Bangalore"]
})

orders = pd.DataFrame({
    "CustomerID": [1, 2, 2, 3, 6],
    "Amount": [500, 1000, 700, 1200, 900]
})

print(pd.merge(customers,orders,on="CustomerID",how="inner"))
print("----------------------------------------")
print(pd.merge(customers,orders,on="CustomerID",how="left"))
print("----------------------------------------")
print(pd.merge(customers,orders,on="CustomerID",how="outer"))
print("----------------------------------------")
left = pd.merge(customers,orders,on="CustomerID",how="left")
print(left[left["Amount"].isnull()])
print("----------------------------------------")
inner = pd.merge(customers,orders,on="CustomerID",how="inner")
print(inner.groupby("CustomerID")["Amount"].sum())

   CustomerID Name    City  Amount
0           1    A   Delhi     500
1           2    B  Mumbai    1000
2           2    B  Mumbai     700
3           3    C   Delhi    1200
----------------------------------------
   CustomerID Name       City  Amount
0           1    A      Delhi   500.0
1           2    B     Mumbai  1000.0
2           2    B     Mumbai   700.0
3           3    C      Delhi  1200.0
4           4    D       Pune     NaN
5           5    E  Bangalore     NaN
----------------------------------------
   CustomerID Name       City  Amount
0           1    A      Delhi   500.0
1           2    B     Mumbai  1000.0
2           2    B     Mumbai   700.0
3           3    C      Delhi  1200.0
4           4    D       Pune     NaN
5           5    E  Bangalore     NaN
6           6  NaN        NaN   900.0
----------------------------------------
   CustomerID Name       City  Amount
4           4    D       Pune     NaN
5           5    E  Bangalore     NaN
----------------------------------------
CustomerID
1     500
2    1700
3    1200
Name: Amount, dtype: int64